# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pwr')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pwr')
    _pwr = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pwr', [dirname(__file__)])
        except ImportError:
            import _pwr
            return _pwr
        if fp is not None:
            try:
                _mod = imp.load_module('_pwr', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pwr = swig_import_helper()
    del swig_import_helper
else:
    import _pwr
del _swig_python_version_info
try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

VENDOR_MAX_STRING_LEN = _pwr.VENDOR_MAX_STRING_LEN
MAJOR_VERSION = _pwr.MAJOR_VERSION
MINOR_VERSION = _pwr.MINOR_VERSION
MAX_STRING_LEN = _pwr.MAX_STRING_LEN
CNTXT_DEFAULT = _pwr.CNTXT_DEFAULT
CNTXT_VENDOR = _pwr.CNTXT_VENDOR
ROLE_APP = _pwr.ROLE_APP
ROLE_MC = _pwr.ROLE_MC
ROLE_OS = _pwr.ROLE_OS
ROLE_USER = _pwr.ROLE_USER
ROLE_RM = _pwr.ROLE_RM
ROLE_ADMIN = _pwr.ROLE_ADMIN
ROLE_MGR = _pwr.ROLE_MGR
ROLE_ACC = _pwr.ROLE_ACC
NUM_ROLES = _pwr.NUM_ROLES
ROLE_INVALID = _pwr.ROLE_INVALID
ROLE_NOT_SPECIFIED = _pwr.ROLE_NOT_SPECIFIED
OBJ_PLATFORM = _pwr.OBJ_PLATFORM
OBJ_CABINET = _pwr.OBJ_CABINET
OBJ_CHASSIS = _pwr.OBJ_CHASSIS
OBJ_BOARD = _pwr.OBJ_BOARD
OBJ_NODE = _pwr.OBJ_NODE
OBJ_SOCKET = _pwr.OBJ_SOCKET
OBJ_CORE = _pwr.OBJ_CORE
OBJ_POWER_PLANE = _pwr.OBJ_POWER_PLANE
OBJ_MEM = _pwr.OBJ_MEM
OBJ_NIC = _pwr.OBJ_NIC
OBJ_TX2_CORE = _pwr.OBJ_TX2_CORE
OBJ_TX2_SRAM = _pwr.OBJ_TX2_SRAM
OBJ_TX2_MEM = _pwr.OBJ_TX2_MEM
OBJ_TX2_SOC = _pwr.OBJ_TX2_SOC
NUM_OBJ_TYPES = _pwr.NUM_OBJ_TYPES
OBJ_INVALID = _pwr.OBJ_INVALID
OBJ_NOT_SPECIFIED = _pwr.OBJ_NOT_SPECIFIED
ATTR_PSTATE = _pwr.ATTR_PSTATE
ATTR_CSTATE = _pwr.ATTR_CSTATE
ATTR_CSTATE_LIMIT = _pwr.ATTR_CSTATE_LIMIT
ATTR_SSTATE = _pwr.ATTR_SSTATE
ATTR_CURRENT = _pwr.ATTR_CURRENT
ATTR_VOLTAGE = _pwr.ATTR_VOLTAGE
ATTR_POWER = _pwr.ATTR_POWER
ATTR_POWER_LIMIT_MIN = _pwr.ATTR_POWER_LIMIT_MIN
ATTR_POWER_LIMIT_MAX = _pwr.ATTR_POWER_LIMIT_MAX
ATTR_FREQ = _pwr.ATTR_FREQ
ATTR_FREQ_LIMIT_MIN = _pwr.ATTR_FREQ_LIMIT_MIN
ATTR_FREQ_LIMIT_MAX = _pwr.ATTR_FREQ_LIMIT_MAX
ATTR_ENERGY = _pwr.ATTR_ENERGY
ATTR_TEMP = _pwr.ATTR_TEMP
ATTR_OS_ID = _pwr.ATTR_OS_ID
ATTR_THROTTLED_TIME = _pwr.ATTR_THROTTLED_TIME
ATTR_THROTTLED_COUNT = _pwr.ATTR_THROTTLED_COUNT
NUM_ATTR_NAMES = _pwr.NUM_ATTR_NAMES
ATTR_INVALID = _pwr.ATTR_INVALID
ATTR_NOT_SPECIFIED = _pwr.ATTR_NOT_SPECIFIED
ATTR_DATA_DOUBLE = _pwr.ATTR_DATA_DOUBLE
ATTR_DATA_UINT64 = _pwr.ATTR_DATA_UINT64
NUM_ATTR_DATA_TYPES = _pwr.NUM_ATTR_DATA_TYPES
ATTR_DATA_INVALID = _pwr.ATTR_DATA_INVALID
ATTR_DATA_NOT_SPECIFIED = _pwr.ATTR_DATA_NOT_SPECIFIED
class AttrAccessError:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AttrAccessError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AttrAccessError, name)
    __repr__ = _swig_repr
    __swig_setmethods__["obj"] = _pwr.AttrAccessError_obj_set
    __swig_getmethods__["obj"] = _pwr.AttrAccessError_obj_get
    __swig_setmethods__["name"] = _pwr.AttrAccessError_name_set
    __swig_getmethods__["name"] = _pwr.AttrAccessError_name_get
    __swig_setmethods__["index"] = _pwr.AttrAccessError_index_set
    __swig_getmethods__["index"] = _pwr.AttrAccessError_index_get
    __swig_setmethods__["error"] = _pwr.AttrAccessError_error_set
    __swig_getmethods__["error"] = _pwr.AttrAccessError_error_get

    def __init__(self):
        this = _pwr.new_AttrAccessError()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pwr.delete_AttrAccessError
    __del__ = lambda self: None
AttrAccessError_swigregister = _pwr.AttrAccessError_swigregister
AttrAccessError_swigregister(AttrAccessError)

MD_NUM = _pwr.MD_NUM
MD_MIN = _pwr.MD_MIN
MD_MAX = _pwr.MD_MAX
MD_PRECISION = _pwr.MD_PRECISION
MD_ACCURACY = _pwr.MD_ACCURACY
MD_UPDATE_RATE = _pwr.MD_UPDATE_RATE
MD_SAMPLE_RATE = _pwr.MD_SAMPLE_RATE
MD_TIME_WINDOW = _pwr.MD_TIME_WINDOW
MD_TS_LATENCY = _pwr.MD_TS_LATENCY
MD_TS_ACCURACY = _pwr.MD_TS_ACCURACY
MD_MAX_LEN = _pwr.MD_MAX_LEN
MD_NAME_LEN = _pwr.MD_NAME_LEN
MD_NAME = _pwr.MD_NAME
MD_DESC_LEN = _pwr.MD_DESC_LEN
MD_DESC = _pwr.MD_DESC
MD_VALUE_LEN = _pwr.MD_VALUE_LEN
MD_VENDOR_INFO_LEN = _pwr.MD_VENDOR_INFO_LEN
MD_VENDOR_INFO = _pwr.MD_VENDOR_INFO
MD_MEASURE_METHOD = _pwr.MD_MEASURE_METHOD
NUM_META_NAMES = _pwr.NUM_META_NAMES
MD_INVALID = _pwr.MD_INVALID
MD_NOT_SPECIFIED = _pwr.MD_NOT_SPECIFIED
RET_WARN_TRUNC = _pwr.RET_WARN_TRUNC
RET_WARN_NO_GRP_BY_NAME = _pwr.RET_WARN_NO_GRP_BY_NAME
RET_WARN_NO_OBJ_AT_INDEX = _pwr.RET_WARN_NO_OBJ_AT_INDEX
RET_WARN_NO_CHILDREN = _pwr.RET_WARN_NO_CHILDREN
RET_WARN_NO_PARENT = _pwr.RET_WARN_NO_PARENT
RET_WARN_NOT_OPTIMIZED = _pwr.RET_WARN_NOT_OPTIMIZED
RET_SUCCESS = _pwr.RET_SUCCESS
RET_FAILURE = _pwr.RET_FAILURE
RET_NOT_IMPLEMENTED = _pwr.RET_NOT_IMPLEMENTED
RET_EMPTY = _pwr.RET_EMPTY
RET_INVALID = _pwr.RET_INVALID
RET_LENGTH = _pwr.RET_LENGTH
RET_NO_ATTRIB = _pwr.RET_NO_ATTRIB
RET_NO_META = _pwr.RET_NO_META
RET_READ_ONLY = _pwr.RET_READ_ONLY
RET_BAD_VALUE = _pwr.RET_BAD_VALUE
RET_BAD_INDEX = _pwr.RET_BAD_INDEX
RET_OP_NOT_ATTEMPTED = _pwr.RET_OP_NOT_ATTEMPTED
RET_NO_PERM = _pwr.RET_NO_PERM
RET_OUT_OF_RANGE = _pwr.RET_OUT_OF_RANGE
TIME_UNINIT = _pwr.TIME_UNINIT
TIME_UNKNOWN = _pwr.TIME_UNKNOWN
class TimePeriod:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TimePeriod, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TimePeriod, name)
    __repr__ = _swig_repr
    __swig_setmethods__["start"] = _pwr.TimePeriod_start_set
    __swig_getmethods__["start"] = _pwr.TimePeriod_start_get
    __swig_setmethods__["stop"] = _pwr.TimePeriod_stop_set
    __swig_getmethods__["stop"] = _pwr.TimePeriod_stop_get
    __swig_setmethods__["instant"] = _pwr.TimePeriod_instant_set
    __swig_getmethods__["instant"] = _pwr.TimePeriod_instant_get

    def __init__(self):
        this = _pwr.new_TimePeriod()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pwr.delete_TimePeriod
    __del__ = lambda self: None
TimePeriod_swigregister = _pwr.TimePeriod_swigregister
TimePeriod_swigregister(TimePeriod)

ATTR_STAT_MIN = _pwr.ATTR_STAT_MIN
ATTR_STAT_MAX = _pwr.ATTR_STAT_MAX
ATTR_STAT_AVG = _pwr.ATTR_STAT_AVG
ATTR_STAT_STDEV = _pwr.ATTR_STAT_STDEV
ATTR_STAT_CV = _pwr.ATTR_STAT_CV
ATTR_STAT_SUM = _pwr.ATTR_STAT_SUM
NUM_ATTR_STATS = _pwr.NUM_ATTR_STATS
ATTR_STAT_INVALID = _pwr.ATTR_STAT_INVALID
ATTR_STAT_NOT_SPECIFIED = _pwr.ATTR_STAT_NOT_SPECIFIED
ID_USER = _pwr.ID_USER
ID_JOB = _pwr.ID_JOB
ID_RUN = _pwr.ID_RUN
NUM_IDS = _pwr.NUM_IDS
ID_INVALID = _pwr.ID_INVALID
ID_NOT_SPECIFIED = _pwr.ID_NOT_SPECIFIED
class OperState:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OperState, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OperState, name)
    __repr__ = _swig_repr
    __swig_setmethods__["c_state_num"] = _pwr.OperState_c_state_num_set
    __swig_getmethods__["c_state_num"] = _pwr.OperState_c_state_num_get
    __swig_setmethods__["p_state_num"] = _pwr.OperState_p_state_num_set
    __swig_getmethods__["p_state_num"] = _pwr.OperState_p_state_num_get

    def __init__(self):
        this = _pwr.new_OperState()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pwr.delete_OperState
    __del__ = lambda self: None
OperState_swigregister = _pwr.OperState_swigregister
OperState_swigregister(OperState)

REGION_DEFAULT = _pwr.REGION_DEFAULT
REGION_SERIAL = _pwr.REGION_SERIAL
REGION_PARALLEL = _pwr.REGION_PARALLEL
REGION_COMPUTE = _pwr.REGION_COMPUTE
REGION_COMMUNICATE = _pwr.REGION_COMMUNICATE
REGION_IO = _pwr.REGION_IO
REGION_MEM_BOUND = _pwr.REGION_MEM_BOUND
NUM_REGION_HINTS = _pwr.NUM_REGION_HINTS
REGION_INVALID = _pwr.REGION_INVALID
REGION_NOT_SPECIFIED = _pwr.REGION_NOT_SPECIFIED
REGION_INT_HIGHEST = _pwr.REGION_INT_HIGHEST
REGION_INT_HIGH = _pwr.REGION_INT_HIGH
REGION_INT_MEDIUM = _pwr.REGION_INT_MEDIUM
REGION_INT_LOW = _pwr.REGION_INT_LOW
REGION_INT_LOWEST = _pwr.REGION_INT_LOWEST
REGION_INT_NONE = _pwr.REGION_INT_NONE
NUM_REGION_INTENSITIES = _pwr.NUM_REGION_INTENSITIES
REGION_INT_INVALID = _pwr.REGION_INT_INVALID
REGION_INT_NOT_SPECIFIED = _pwr.REGION_INT_NOT_SPECIFIED
SLEEP_NO = _pwr.SLEEP_NO
SLEEP_SHALLOW = _pwr.SLEEP_SHALLOW
SLEEP_MEDIUM = _pwr.SLEEP_MEDIUM
SLEEP_DEEP = _pwr.SLEEP_DEEP
SLEEP_DEEPEST = _pwr.SLEEP_DEEPEST
NUM_SLEEP_STATES = _pwr.NUM_SLEEP_STATES
SLEEP_INVALID = _pwr.SLEEP_INVALID
SLEEP_NOT_SPECIFIED = _pwr.SLEEP_NOT_SPECIFIED
PERF_FASTEST = _pwr.PERF_FASTEST
PERF_FAST = _pwr.PERF_FAST
PERF_MEDIUM = _pwr.PERF_MEDIUM
PERF_SLOW = _pwr.PERF_SLOW
PERF_SLOWEST = _pwr.PERF_SLOWEST
NUM_PERF_STATES = _pwr.NUM_PERF_STATES
PERF_INVALID = _pwr.PERF_INVALID
PERF_NOT_SPECIFIED = _pwr.PERF_NOT_SPECIFIED
RET_IPC = _pwr.RET_IPC
RET_STATUS = _pwr.RET_STATUS
class StatTimes:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StatTimes, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StatTimes, name)
    __repr__ = _swig_repr
    __swig_setmethods__["start"] = _pwr.StatTimes_start_set
    __swig_getmethods__["start"] = _pwr.StatTimes_start_get
    __swig_setmethods__["stop"] = _pwr.StatTimes_stop_set
    __swig_getmethods__["stop"] = _pwr.StatTimes_stop_get
    __swig_setmethods__["instant"] = _pwr.StatTimes_instant_set
    __swig_getmethods__["instant"] = _pwr.StatTimes_instant_get

    def __init__(self):
        this = _pwr.new_StatTimes()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pwr.delete_StatTimes
    __del__ = lambda self: None
StatTimes_swigregister = _pwr.StatTimes_swigregister
StatTimes_swigregister(StatTimes)


def GetMajorVersion():
    return _pwr.GetMajorVersion()
GetMajorVersion = _pwr.GetMajorVersion

def GetMinorVersion():
    return _pwr.GetMinorVersion()
GetMinorVersion = _pwr.GetMinorVersion

def CntxtInit(arg1, arg2, name, arg4):
    return _pwr.CntxtInit(arg1, arg2, name, arg4)
CntxtInit = _pwr.CntxtInit

def CntxtDestroy(arg1):
    return _pwr.CntxtDestroy(arg1)
CntxtDestroy = _pwr.CntxtDestroy

def CntxtGetEntryPoint(arg1, arg2):
    return _pwr.CntxtGetEntryPoint(arg1, arg2)
CntxtGetEntryPoint = _pwr.CntxtGetEntryPoint

def CntxtGetGrpByType(arg1, arg2, arg3):
    return _pwr.CntxtGetGrpByType(arg1, arg2, arg3)
CntxtGetGrpByType = _pwr.CntxtGetGrpByType

def CntxtGetGrpByName(arg1, name, arg3):
    return _pwr.CntxtGetGrpByName(arg1, name, arg3)
CntxtGetGrpByName = _pwr.CntxtGetGrpByName

def CntxtGetObjByName(arg1, name, arg3):
    return _pwr.CntxtGetObjByName(arg1, name, arg3)
CntxtGetObjByName = _pwr.CntxtGetObjByName

def ObjGetType(arg1, arg2):
    return _pwr.ObjGetType(arg1, arg2)
ObjGetType = _pwr.ObjGetType

def ObjGetName(arg1, arg2, arg3):
    return _pwr.ObjGetName(arg1, arg2, arg3)
ObjGetName = _pwr.ObjGetName

def ObjGetParent(arg1, arg2):
    return _pwr.ObjGetParent(arg1, arg2)
ObjGetParent = _pwr.ObjGetParent

def ObjGetChildren(arg1, arg2):
    return _pwr.ObjGetChildren(arg1, arg2)
ObjGetChildren = _pwr.ObjGetChildren

def ObjAttrIsValid(arg1, name):
    return _pwr.ObjAttrIsValid(arg1, name)
ObjAttrIsValid = _pwr.ObjAttrIsValid

def ObjAttrGetValue(arg1, arg2):
    return _pwr.ObjAttrGetValue(arg1, arg2)
ObjAttrGetValue = _pwr.ObjAttrGetValue

def ObjAttrSetValue(arg1, name, INPUT):
    return _pwr.ObjAttrSetValue(arg1, name, INPUT)
ObjAttrSetValue = _pwr.ObjAttrSetValue

def PWR_ObjAttrGetValues(arg1, count, names, buf, ts, arg6):
    return _pwr.PWR_ObjAttrGetValues(arg1, count, names, buf, ts, arg6)
PWR_ObjAttrGetValues = _pwr.PWR_ObjAttrGetValues

def PWR_ObjAttrSetValues(arg1, count, names, buf, arg5):
    return _pwr.PWR_ObjAttrSetValues(arg1, count, names, buf, arg5)
PWR_ObjAttrSetValues = _pwr.PWR_ObjAttrSetValues

def GrpCreate(arg1, arg2):
    return _pwr.GrpCreate(arg1, arg2)
GrpCreate = _pwr.GrpCreate

def GrpDestroy(arg1):
    return _pwr.GrpDestroy(arg1)
GrpDestroy = _pwr.GrpDestroy

def GrpGetNumObjs(arg1):
    return _pwr.GrpGetNumObjs(arg1)
GrpGetNumObjs = _pwr.GrpGetNumObjs

def GrpGetObjByIndx(arg1, arg2, arg3):
    return _pwr.GrpGetObjByIndx(arg1, arg2, arg3)
GrpGetObjByIndx = _pwr.GrpGetObjByIndx

def GrpAddObj(arg1, arg2):
    return _pwr.GrpAddObj(arg1, arg2)
GrpAddObj = _pwr.GrpAddObj

def GrpRemoveObj(arg1, arg2):
    return _pwr.GrpRemoveObj(arg1, arg2)
GrpRemoveObj = _pwr.GrpRemoveObj

def GrpAttrSetValue(arg1, name, INPUT, arg4):
    return _pwr.GrpAttrSetValue(arg1, name, INPUT, arg4)
GrpAttrSetValue = _pwr.GrpAttrSetValue

def GrpAttrGetValue(arg1, name, ts, arg5):
    return _pwr.GrpAttrGetValue(arg1, name, ts, arg5)
GrpAttrGetValue = _pwr.GrpAttrGetValue

def GrpAttrSetValues(arg1, count, names, buf, arg5):
    return _pwr.GrpAttrSetValues(arg1, count, names, buf, arg5)
GrpAttrSetValues = _pwr.GrpAttrSetValues

def GrpAttrGetValues(arg1, count, names, buf, ts, arg6):
    return _pwr.GrpAttrGetValues(arg1, count, names, buf, ts, arg6)
GrpAttrGetValues = _pwr.GrpAttrGetValues

def StatusCreate(arg1, arg2):
    return _pwr.StatusCreate(arg1, arg2)
StatusCreate = _pwr.StatusCreate

def StatusDestroy(arg1):
    return _pwr.StatusDestroy(arg1)
StatusDestroy = _pwr.StatusDestroy

def StatusPopError(arg1, arg2):
    return _pwr.StatusPopError(arg1, arg2)
StatusPopError = _pwr.StatusPopError

def StatusClear(arg1):
    return _pwr.StatusClear(arg1)
StatusClear = _pwr.StatusClear

def ObjCreateStat(arg1, name, stat, arg4):
    return _pwr.ObjCreateStat(arg1, name, stat, arg4)
ObjCreateStat = _pwr.ObjCreateStat

def GrpCreateStat(arg1, name, stat, arg4):
    return _pwr.GrpCreateStat(arg1, name, stat, arg4)
GrpCreateStat = _pwr.GrpCreateStat

def StatDestroy(arg1):
    return _pwr.StatDestroy(arg1)
StatDestroy = _pwr.StatDestroy

def StatStart(arg1):
    return _pwr.StatStart(arg1)
StatStart = _pwr.StatStart

def StatStop(arg1):
    return _pwr.StatStop(arg1)
StatStop = _pwr.StatStop

def StatClear(arg1):
    return _pwr.StatClear(arg1)
StatClear = _pwr.StatClear

def PWR_StatGetValue(arg1):
    return _pwr.PWR_StatGetValue(arg1)
PWR_StatGetValue = _pwr.PWR_StatGetValue

def StatGetValues(arg1, values, statTimes):
    return _pwr.StatGetValues(arg1, values, statTimes)
StatGetValues = _pwr.StatGetValues

def ObjGetTypeString(arg1):
    return _pwr.ObjGetTypeString(arg1)
ObjGetTypeString = _pwr.ObjGetTypeString

def AttrGetTypeString(arg1):
    return _pwr.AttrGetTypeString(arg1)
AttrGetTypeString = _pwr.AttrGetTypeString

def TimeConvert(time):
    return _pwr.TimeConvert(time)
TimeConvert = _pwr.TimeConvert


def ObjAttrGetValues( self, names, status ):
	return _ObjAttrGetValues( self, len(names), names, status )

def ObjAttrSetValues( self, names, values, status ):
	return _ObjAttrSetValues( self, len(names), names, values, status )

def StatGetValue( coreStat ):
	retval, value, x = PWR_StatGetValue( coreStat )

	timeStat = TimePeriod()
	timeStat.start = x['start'] 
	timeStat.stop = x['stop'] 
	timeStat.instant = x['instant'] 

	return retval, value, timeStat  



def _ObjAttrGetValues(arg1, arg2, InValue, arg6):
    return _pwr._ObjAttrGetValues(arg1, arg2, InValue, arg6)
_ObjAttrGetValues = _pwr._ObjAttrGetValues

def _ObjAttrSetValues(arg1, arg2, arg3, arg4, arg5):
    return _pwr._ObjAttrSetValues(arg1, arg2, arg3, arg4, arg5)
_ObjAttrSetValues = _pwr._ObjAttrSetValues


